# Generated by Django 3.2.1 on 2021-05-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermeta',
            name='order_date',
            field=models.DateTimeField(verbose_name='date order'),
        ),
    ]
