# Generated by Django 3.2.1 on 2021-05-06 07:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordermeta_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[300, 300], upload_to='uploads/'),
        ),
    ]
