# Generated by Django 3.2.1 on 2021-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
