# Generated by Django 3.2.1 on 2021-05-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-pub_date',)},
        ),
    ]
